# Default values for promo-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: promo-api
namespace: dev

deployment:
  image: "myregistry/promo-api:1.1.1-SNAPSHOT"
  imagePullPolicy: "Always"

  profile: "dev"

  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 128Mi
      
service:
  scrapeable: "true"