{{- define "librarychart.service.tpl" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: {{ .Values.name }}
{{- end -}}
{{- define "librarychart.service" -}}
{{- include "librarychart.util.merge" (append . "librarychart.service.tpl") -}}
{{- end -}}